version: '3.9'

services:
  app:
    image: value_backend_app
    container_name: value_backend_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    volumes:
      - ./.bin/:/root/
      - ./configs/:/root/configs/
      - ./templates/:/root/templates/
    env_file:
      - .env

  mongodb:
    image: mongo:4.4-bionic
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=valueDB
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=qwerty
    volumes:
      - ./.data/db:/data/db
    ports:
      - 27018:27017